# Generated by Django 5.0.1 on 2024-02-10 23:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_naissance', models.DateField(null=True)),
                ('universite_provenance', models.CharField(choices=[('IAI', 'Iai Togo'), ('UL', 'Universite De Lome'), ('UC', 'Ucao Uut'), ('IS', 'Isdi'), ('FMT', 'Formatec'), ('LBS', 'Lome Buisness School'), ('ISM', 'Ismad'), ('DFT', 'Defitech'), ('ISF', 'Isfodeme'), ('IM', 'Istm'), ('IA', 'Isla'), ('ETB', 'Estabat'), ('CFP', 'Cifop'), ('EC', 'Ecole Des Cadres')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_naissance', models.DateField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=30, unique=True)),
                ('libelle', models.CharField(max_length=50, null=True)),
                ('contenue_texte', models.TextField(null=True)),
                ('urls', models.TextField(null=True)),
                ('etudiants', models.ManyToManyField(related_name='cours', to='backend.etudiant')),
                ('professeurs', models.ManyToManyField(related_name='cours', to='backend.professeur')),
            ],
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_Inscription', models.DateField()),
                ('status', models.CharField(choices=[('E_C', 'En Cours'), ('E_A', 'En Attente'), ('VL', 'Valide'), ('AN', 'Annulee')], default='E_C', max_length=25)),
                ('id_cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.cours')),
                ('id_etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.etudiant')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('libelle', models.CharField(max_length=30)),
                ('cours', models.ManyToManyField(related_name='modules', to='backend.cours')),
            ],
        ),
        migrations.CreateModel(
            name='Contenir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.cours')),
                ('id_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.module')),
            ],
        ),
        migrations.CreateModel(
            name='Enseigner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_Debut', models.DateField()),
                ('session_Fin', models.DateField()),
                ('volume_Horaire', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(60)])),
                ('id_cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.cours')),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.professeur')),
            ],
        ),
    ]
