# Generated by Django 5.0.1 on 2024-02-18 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_inscription_id_session'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enseigner',
            old_name='id_cours',
            new_name='cours',
        ),
        migrations.RenameField(
            model_name='enseigner',
            old_name='id_professeur',
            new_name='professeur',
        ),
        migrations.RemoveField(
            model_name='cours',
            name='etudiants',
        ),
        migrations.RemoveField(
            model_name='cours',
            name='professeurs',
        ),
        migrations.RemoveField(
            model_name='module',
            name='cours',
        ),
        migrations.AddField(
            model_name='enseigner',
            name='id_Session',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inscription',
            name='id_Session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.enseigner'),
        ),
    ]
