# Generated by Django 5.0.1 on 2024-03-05 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_cours_modules_module_cours_delete_contenir'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inscription',
            old_name='id_cours',
            new_name='cours',
        ),
        migrations.RenameField(
            model_name='inscription',
            old_name='id_etudiant',
            new_name='etudiant',
        ),
    ]
