# Generated by Django 5.0.1 on 2024-03-05 03:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_rename_id_cours_inscription_cours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='date_Inscription',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='id_Session',
            field=models.IntegerField(),
        ),
    ]
